### PR TITLE
new Template system

### PR DESCRIPTION
**Pull request by Phhere**
This replaces the old template system which was based on eval() with a new one
It should be equal on performance and a little bit faster if the same template is rendered multiple times
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Pascalmh%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/154%23issuecomment-69619024%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-12T18%3A28%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%2C%20%7B%22body%22%3A%20%22Notice%3A%20Array%20to%20string%20conversion%20in%20src/func/template.php%20on%20line%2071%5Cr%5Cn%5Cr%5CnURL%3A%20index.php%3Fsite%3Dforum_topic%26topic%3D1%22%2C%20%22created_at%22%3A%20%222015-01-12T21%3A55%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22Can%20not%20reproduce%20it%20%40derchrisuk%20-%20tried%20as%20Admin%20and%20Guest.%20Also%20looked%20at%20the%20forum_topics.php%20and%20could%20not%20find%20the%20mistake.%22%2C%20%22created_at%22%3A%20%222015-01-13T11%3A56%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%2C%20%7B%22body%22%3A%20%22The%20problem%20is%20with%20the%20%60forum_topics_title%60%20template.%5Cr%5Cn%5Cr%5CnBoth%20%60%24kathname%60%20and%20%60%24boardname%60%20are%20correct%20parsed%20in%20the%20template%2C%20but%20the%20links%20are%20not%3A%5Cr%5Cn%5Cr%5Cn%60index.php%3Fsite%3Dforum%26amp%3Bcat%3D%7BArray%5B%27category%27%5D%7D%60%5Cr%5Cn%60index.php%3Fsite%3Dforum%26amp%3Bboard%3D%7BArray%5B%27boardID%27%5D%7D%60%22%2C%20%22created_at%22%3A%20%222015-01-13T12%3A28%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22Combine%20all%20templates%20for%20one%20view%20into%20single%20html%20file%20with%20comments%20as%20seperator%22%2C%20%22created_at%22%3A%20%222015-01-13T19%3A23%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Phhere%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-01-17T21%3A15%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Phhere%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/154%23issuecomment-69619024%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/154%23issuecomment-69653909%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/154%23issuecomment-69733801%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/154%23issuecomment-69737317%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/154%23issuecomment-69802768%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/154%23issuecomment-70384704%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/Pascalmh'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/154#issuecomment-69619024'>General Comment</a></b>
- <a href='https://github.com/Pascalmh'></a> :shipit:
- <a href='https://github.com/derchrisuk'></a> Notice: Array to string conversion in src/func/template.php on line 71
URL: index.php?site=forum_topic&topic=1
- <a href='https://github.com/Pascalmh'></a> Can not reproduce it @derchrisuk - tried as Admin and Guest. Also looked at the forum_topics.php and could not find the mistake.
- <a href='https://github.com/derchrisuk'></a> The problem is with the `forum_topics_title` template.
Both `$kathname` and `$boardname` are correct parsed in the template, but the links are not:
`index.php?site=forum&amp;cat={Array['category']}`
`index.php?site=forum&amp;board={Array['boardID']}`
- <a href='https://github.com/Phhere'></a> Combine all templates for one view into single html file with comments as seperator

<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/154?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/154?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/154?approve=0'></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/154'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by derchrisuk** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/154'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Pascalmh** [comment]
:shipit:

**Comment by derchrisuk** [comment]
Notice: Array to string conversion in src/func/template.php on line 71

URL: index.php?site=forum_topic&topic=1

**Comment by Pascalmh** [comment]
Can not reproduce it @derchrisuk - tried as Admin and Guest. Also looked at the forum_topics.php and could not find the mistake.

**Comment by derchrisuk** [comment]
The problem is with the `forum_topics_title` template.

Both `$kathname` and `$boardname` are correct parsed in the template, but the links are not:

`index.php?site=forum&amp;cat={Array['category']}`
`index.php?site=forum&amp;board={Array['boardID']}`

**Comment by Phhere** [comment]
Combine all templates for one view into single html file with comments as seperator

**Comment by Phhere** [comment]
:+1:

**Pull request merged**
