### PR TITLE
fix(date) make dates usable in the future

### PR DESCRIPTION
**Pull request by Pascalmh**
Dates can now be added from (now - 5 years) to (now + 1 year) or vise versa (which ever makes sense)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/184%23issuecomment-70893057%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/184%23issuecomment-70920035%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/184%23issuecomment-71277856%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/184%23issuecomment-70893057%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22There%20are%20more%20date%20inputs%20like%20calendar%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-01-21T18%3A28%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Phhere%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-01-21T20%3A57%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-23T22%3A31%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Phhere%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/Phhere%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/Phhere'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/184#issuecomment-70893057'>General Comment</a></b>
- <a href='https://github.com/Phhere'></a> There are more date inputs like calendar

<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/184?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/184?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/184?approve=0'></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/184'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by derchrisuk** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/184'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Phhere** [comment]
There are more date inputs like calendar

**Comment by Pascalmh** [comment]
:+1:

**Comment by Phhere** [comment]
:shipit:

**Pull request merged**
