### PR TITLE
fix(php) readd and delete buddy query failed fixed

### PR DESCRIPTION
**Pull request by blu3bird23**
fixed a query failed if you readd or delete a buddy
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/156%23issuecomment-69524075%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/156%23issuecomment-69590963%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/156%23issuecomment-69595100%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/156%23issuecomment-69524075%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Add%20a%20space%20before%20and%20after%20the%20%60.%60%20and%20I%20will%20merge%2C%20thank%20you.%5Cr%5Cn%5Cr%5Cn%60buddy%3D%27%5C%22%20.%20%28int%29%24_GET%5B%20%27id%27%20%5D.%5C%22%27%5C%22%60%20should%20become%3A%5Cr%5Cn%60buddy%3D%27%5C%22%20.%20%28int%29%24_GET%5B%20%27id%27%20%5D%20.%20%5C%22%27%5C%22%60%22%2C%20%22created_at%22%3A%20%222015-01-12T02%3A20%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%2C%20%7B%22body%22%3A%20%22Done%20%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-01-12T15%3A53%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5761799%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/blu3bird23%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-12T16%3A15%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/derchrisuk%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/derchrisuk'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/156#issuecomment-69524075'>General Comment</a></b>
- <a href='https://github.com/Pascalmh'></a> Add a space before and after the `.` and I will merge, thank you.
`buddy='" . (int)$_GET[ 'id' ]."'"` should become:
`buddy='" . (int)$_GET[ 'id' ] . "'"`
- <a href='https://github.com/blu3bird23'></a> Done :+1:

<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/156?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/156?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/156?approve=0'></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/156'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by derchrisuk** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/156'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Pascalmh** [comment]
Add a space before and after the `.` and I will merge, thank you.

`buddy='" . (int)$_GET[ 'id' ]."'"` should become:
`buddy='" . (int)$_GET[ 'id' ] . "'"`

**Comment by blu3bird23** [comment]
Done :+1:

**Comment by derchrisuk** [comment]
:shipit:

**Pull request merged**
