### PR TITLE
Link h2 in title  html to main page #106

### PR DESCRIPTION
**Pull request by DDaems**
changed all titles to links
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/131%23issuecomment-69447299%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/131%23issuecomment-69458424%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/131%23issuecomment-69463845%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/131%23issuecomment-69482297%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/131%23issuecomment-69447299%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Ok%2C%20i%27m%20just%20going%20to%20leave%20it%20as%20it%20is.%5Cr%5CnI%27ll%20try%20to%20install%20grunt%20and%20composer%20next%20time%20and%20validate%20before%20making%20any%20commits.%5Cr%5CnDidn%27t%20expect%20it%20to%20be%20trowing%20errors%20on%20tabs%20and%20stuff.%20My%20bad%20for%20not%20doing%20this.%22%2C%20%22created_at%22%3A%20%222015-01-10T07%3A34%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7575436%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/DDaems%22%7D%7D%2C%20%7B%22body%22%3A%20%22We%20could%20cherry-pick%20this%20commit%20https%3A//github.com/DDaems/webSPELL-4.2.3/commit/a979ed5a63c28706c3e3127af4eefe1b857ca8df%20as%20the%20other%20commits%20do%20not%20belong%20into%20this%20PR%20-%20however%2C%20the%20a-Tag%20should%20go%20inside%20of%20the%20h2-Tag%20and%20not%20the%20other%20way%20arround%2C%20can%20you%20change%20that%20-%20I%20will%20cherry-pick%20it%20then%20and%20we%20can%20close%20this%20PR.%22%2C%20%22created_at%22%3A%20%222015-01-10T14%3A55%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20though%20it%20wouldn%27t%20make%20a%20big%20difference%2C%20but%20after%20looking%20it%20up.%5Cr%5CnI%20was%20wrong%2C%20i%27ll%20change%20it%20as%20soon%20as%20i%20get%20the%20time%20to%20do%20so.%20%3B-%29%22%2C%20%22created_at%22%3A%20%222015-01-10T17%3A30%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7575436%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/DDaems%22%7D%7D%2C%20%7B%22body%22%3A%20%22Ok%20i%20fixed%20the%20a%20tags.%5Cr%5Cn%5Cr%5CnJust%20to%20note%3A%5Cr%5Cni%20have%20no%20idea%2C%20why%20this%20commit%3A%5Cr%5CnChecklogin%20-%20Replace%20Error%20Message%20%23119%20with%20bootstrap%20style%5Cr%5Cnis%20in%20here.%20So%20maybe%20its%20better%20to%20first%20pass%20this%20and%20than%20the%20other%20one%20i%20updated.%5Cr%5CnWith%20a%20flexbox%20approach.%22%2C%20%22created_at%22%3A%20%222015-01-11T03%3A34%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7575436%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/DDaems%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/131#issuecomment-69447299'>General Comment</a></b>
- <a href='https://github.com/DDaems'></a> Ok, i'm just going to leave it as it is.
I'll try to install grunt and composer next time and validate before making any commits.
Didn't expect it to be trowing errors on tabs and stuff. My bad for not doing this.
- <a href='https://github.com/Pascalmh'></a> We could cherry-pick this commit https://github.com/DDaems/webSPELL-4.2.3/commit/a979ed5a63c28706c3e3127af4eefe1b857ca8df as the other commits do not belong into this PR - however, the a-Tag should go inside of the h2-Tag and not the other way arround, can you change that - I will cherry-pick it then and we can close this PR.
- <a href='https://github.com/DDaems'></a> I though it wouldn't make a big difference, but after looking it up.
I was wrong, i'll change it as soon as i get the time to do so. ;-)
- <a href='https://github.com/DDaems'></a> Ok i fixed the a tags.
Just to note:
i have no idea, why this commit:
Checklogin - Replace Error Message #119 with bootstrap style
is in here. So maybe its better to first pass this and than the other one i updated.
With a flexbox approach.

<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/131?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/131?approve=1'></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/131'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by derchrisuk** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/131'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by DDaems** [comment]
Ok, i'm just going to leave it as it is.
I'll try to install grunt and composer next time and validate before making any commits.
Didn't expect it to be trowing errors on tabs and stuff. My bad for not doing this.

**Comment by Pascalmh** [comment]
We could cherry-pick this commit https://github.com/DDaems/webSPELL-4.2.3/commit/a979ed5a63c28706c3e3127af4eefe1b857ca8df as the other commits do not belong into this PR - however, the a-Tag should go inside of the h2-Tag and not the other way arround, can you change that - I will cherry-pick it then and we can close this PR.

**Comment by DDaems** [comment]
I though it wouldn't make a big difference, but after looking it up.
I was wrong, i'll change it as soon as i get the time to do so. ;-)

**Comment by DDaems** [comment]
Ok i fixed the a tags.

Just to note:
i have no idea, why this commit:
Checklogin - Replace Error Message #119 with bootstrap style
is in here. So maybe its better to first pass this and than the other one i updated.
With a flexbox approach.

**Comment by Pascalmh** [comment]
33dee9fd1f5ad4bdca2bfcfed381c7bc222d856f

**Comment by Pascalmh** [comment]
:+1:

**Pull request closed without merging**
