### PR TITLE
Updated articles

### PR DESCRIPTION
**Pull request by Phhere**
fixes post/edit layout
added inputs for tags
fix js errors
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/178%23issuecomment-70406289%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/178%23issuecomment-70406412%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/178%23issuecomment-70406454%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/178%23issuecomment-70406562%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/178%23issuecomment-70406289%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Small%20preview%5Cr%5Cn%21%5Bedit_1%5D%28https%3A//cloud.githubusercontent.com/assets/1415280/5792342/2a96725a-9f15-11e4-91d0-9c40dbc36ae1.png%29%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-01-18T12%3A23%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Phhere%22%7D%7D%2C%20%7B%22body%22%3A%20%22http%3A//maxwells.github.io/bootstrap-tags.html%20%3F%21%22%2C%20%22created_at%22%3A%20%222015-01-18T12%3A26%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2109906%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/xxxrenegade%22%7D%7D%2C%20%7B%22body%22%3A%20%22Nice%20idea%20but%20i%20am%20not%20sure%20if%20we%20want%20to%20include%20more%20external%20libraries%22%2C%20%22created_at%22%3A%20%222015-01-18T12%3A27%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Phhere%22%7D%7D%2C%20%7B%22body%22%3A%20%22Ja%20das%20wahr%20auch%20meine%20%5Cu00dcberlegung%2C%20es%20w%5Cu00fcrde%20die%20Usability%20aber%20schon%20sehr%20verbessern.%22%2C%20%22created_at%22%3A%20%222015-01-18T12%3A30%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2109906%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/xxxrenegade%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/178#issuecomment-70406289'>General Comment</a></b>
- <a href='https://github.com/Phhere'></a> Small preview
edit_1
- <a href='https://github.com/xxxrenegade'></a> http://maxwells.github.io/bootstrap-tags.html ?!
- <a href='https://github.com/Phhere'></a> Nice idea but i am not sure if we want to include more external libraries
- <a href='https://github.com/xxxrenegade'></a> Ja das wahr auch meine Überlegung, es würde die Usability aber schon sehr verbessern.

<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/178?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/178?approve=1'></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/178'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by derchrisuk** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/178'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Phhere** [comment]
Small preview
edit_1

**Comment by xxxrenegade** [comment]
http://maxwells.github.io/bootstrap-tags.html ?!

**Comment by Phhere** [comment]
Nice idea but i am not sure if we want to include more external libraries

**Comment by xxxrenegade** [comment]
Ja das wahr auch meine Überlegung, es würde die Usability aber schon sehr verbessern.

**Pull request merged**
