### PR TITLE
fix(php) missing namespace added

### PR DESCRIPTION
**Pull request by blu3bird23**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/170%23issuecomment-69835261%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/170%23issuecomment-69930556%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/170%23issuecomment-69930685%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/170%23issuecomment-69930981%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/170%23issuecomment-69835261%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22You%20should%20have%20done%20a%20rebase%20before%20committing%20the%20changes%20and%20open%20the%20PR.%5Cr%5CnThis%20would%20have%20avoided%20commit%2014de68dae72d8f68c061f6efa85e61c91784e996%22%2C%20%22created_at%22%3A%20%222015-01-13T22%3A38%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22should%20be%20ok%20now.%20some%20issues%20with%20git%20%3A/%22%2C%20%22created_at%22%3A%20%222015-01-14T15%3A15%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5761799%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/blu3bird23%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-14T15%3A16%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-14T15%3A18%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/Pascalmh%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/derchrisuk%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/Pascalmh'></a><a href='https://github.com/derchrisuk'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/170#issuecomment-69835261'>General Comment</a></b>
- <a href='https://github.com/derchrisuk'></a> You should have done a rebase before committing the changes and open the PR.
This would have avoided commit 14de68dae72d8f68c061f6efa85e61c91784e996
- <a href='https://github.com/blu3bird23'></a> should be ok now. some issues with git :/

<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/170?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/170?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/170?approve=0'></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/170'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by derchrisuk** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/170'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by derchrisuk** [comment]
You should have done a rebase before committing the changes and open the PR.
This would have avoided commit 14de68dae72d8f68c061f6efa85e61c91784e996

**Comment by blu3bird23** [comment]
should be ok now. some issues with git :/

**Comment by Pascalmh** [comment]
:shipit:

**Comment by derchrisuk** [comment]
:shipit:

**Pull request merged**
